### ISSUE TITLE
Won't install on laravel 9

### ISSUE THREAD

**Issue by ZARk-be** [josegus/laravel-flash#1]
Hello

There's a requirements error with Laravel 9

Any plans on updating ?

**Comment by josegus** [comment]
I haven't had enough time to maintain this package. I'd do it as soon as I can. If you wish, feel free to send a PR to upgrade to Laravel 9 :smile:

**Comment by soap** [comment]
I will try to make PR to support Laravel 9. Hopefully, it will finish by this week.

**Comment by soap** [comment]
@josegus after upgrading, I installed on L9 and it works if I use @include('flash::message') but not with <x-flash:message />. I cannot find where you register the blade component.

**Comment by josegus** [comment]
@ZARk-be @soap Sorry for the delay. Try installing again please, I just upgraded the package to support Laravel 9.

**Comment by josegus** [comment]
> @josegus after upgrading, I installed on L9 and it works if I use @include('flash::message') but not with <x-flash:message />. I cannot find where you register the blade component.

I tested component view in a clean Laravel 9 project. Check your code please, you might have an error or maybe you forgot to use ":" twice `<x-flash::message />`

**Comment by josegus** [comment]
@soap @ZARk-be  I'm closing, I tested and it works for me. Feel free to open a new issue anytime.
