### ISSUE TITLE
Automatic dismissal after a few seconds

### ISSUE THREAD

**Issue by mrseewhy** [josegus/laravel-flash#5]
Can you make it so that it can automatically get dismissed after a few seconds.

**Comment by josegus** [comment]
I can, but unfortunately, right now I don't have enough free time to maintain this package. Feel free to create a PR and I'll approve it.

**Comment by josegus** [comment]
Also, you can publish the views from the package and write a small script to make it dismissable.

**Comment by mrseewhy** [comment]
Have you checked my PR?

**Comment by josegus** [comment]
@mrseewhy I answered your request, please check your PR.

**Comment by mrseewhy** [comment]
I sincerely apologize if you see it that way. This is my first open-source
contribution, I am just getting familiar with Laravel to a deep level, I
mean beyond CRUD itself. I went through your code, and my intention was to
add a class that can be called which will take an argument for time in
milliseconds. However, I don't know how I can do that with your existing
code, which was why I did what I did. Apologies once again.
